### ISSUE TITLE
CPU_Temperature method isn't working

### ISSUE THREAD

**Issue by lg13826** [RyanLuong1/group_8_project#2]
I think the syntax is wrong, I'm able to get the memory location of the function if i remove the paranthesis but the function itself doesn't work.

**Comment by RyanLuong1** [comment]
Did you ran it on Linux or Window?

**Comment by lg13826** [comment]
Linux
Error is
**TypeError: unhashable type: 'dict'**

**Comment by RyanLuong1** [comment]
Yeah so the function itself already returns a dictionary so what is happening is that it returns a dictionary of a dictionary which I think isn't supported in general. But since we are developing on Windows, we need to find another way. But we can remove the {} from the return statement.

**Comment by lg13826** [comment]
Modifying it on my end and removing the brackets worked, but there's no values being returns which might be because i'm doing it on WSL.

**Comment by RyanLuong1** [comment]
That's fine. Make a pull request so we can merge it and in the meantime, can you find another way to get the CPU temperature?
https://github.com/RyanLuong1/group_8_project/issues/7. I mentioned this in another issue and someone else did this to find the temperature but we can use it to find other information we can't already.
